import type {
  AdminPointEntry,
  AdminStats,
  AdminUser,
  Coupon,
  DownloadHistory,
  OwnedProduct,
  PointEntry,
  Product,
  Transaction,
  User,
} from '@/types'

function daysAgo(n: number) {
  return new Date(Date.now() - n * 86_400_000).toISOString()
}

export const mockUser: User = {
  id: 'usr_01',
  name: 'Rizky Pratama',
  email: 'rizky@example.com',
  whatsapp: '081234567890',
  role: 'member',
  points: 1357,
  avatar: null,
  createdAt: daysAgo(96),
}

export const mockAdmin: User = {
  id: 'usr_admin',
  name: 'Admin Nura',
  email: 'admin@example.com',
  whatsapp: '081200001111',
  role: 'admin',
  points: 0,
  avatar: null,
  createdAt: daysAgo(420),
}

export const mockProducts: Product[] = [
  {
    id: 'prd_01',
    slug: 'canva-social-media-kit-pro',
    title: 'Social Media Kit Pro — 300 Template Canva',
    category: 'canva',
    price: 149_000,
    originalPrice: 299_000,
    downloadType: 'external',
    downloadUrl:
      'https://drive.google.com/file/d/1GrafistaDemoKitPro300/view?usp=sharing',
    shortDescription:
      '300 template feed, story, dan carousel siap edit untuk brand kamu.',
    description:
      'Koleksi lengkap 300 template Canva yang dirancang untuk kebutuhan konten harian brand dan personal. Setiap template dibuat dengan grid konsisten, tipografi rapi, dan palet warna yang mudah disesuaikan hanya dalam beberapa klik. Cocok untuk agensi, UMKM, maupun content creator yang butuh output cepat tanpa mengorbankan kualitas visual.',
    cover:
      'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=900&q=80',
    highlights: [
      '300 template (feed, story, carousel, highlight cover)',
      'Editable 100% di Canva Free & Pro',
      'Panduan brand color swap 1 klik',
      'Update gratis selamanya',
    ],
    includes: [
      { label: 'Format', value: 'Canva Template Link' },
      { label: 'Jumlah Aset', value: '300 halaman' },
      { label: 'Lisensi', value: 'Personal & Komersial' },
    ],
    fileSize: 184_000_000,
    fileType: 'ZIP + Canva Link',
    version: '3.2.0',
    rating: 4.9,
    sales: 1284,
    updatedAt: daysAgo(6),
  },
  {
    id: 'prd_02',
    slug: 'elementor-agency-landing-pack',
    title: 'Elementor Agency Landing Pack',
    category: 'elementor',
    price: 249_000,
    originalPrice: 450_000,
    downloadType: 'upload',
    fileName: 'elementor-agency-landing-pack-2.4.1.zip',
    isActive: false,
    shortDescription:
      '12 landing page premium untuk agensi, SaaS, dan personal brand.',
    description:
      'Paket template Elementor dengan 12 landing page yang sudah dioptimasi untuk konversi dan Core Web Vitals. Semua section modular sehingga bisa disusun ulang menjadi ratusan kombinasi halaman. Tidak memerlukan plugin berbayar tambahan selain Elementor Free.',
    cover:
      'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=900&q=80',
    highlights: [
      '12 landing page + 60 section modular',
      'Responsive breakpoint sudah dirapikan',
      'Optimasi kecepatan (LCP < 2.5s)',
      'One-click import template kit',
    ],
    includes: [
      { label: 'Format', value: 'JSON Template Kit' },
      { label: 'Kompatibilitas', value: 'Elementor 3.20+' },
      { label: 'Lisensi', value: 'Unlimited project' },
    ],
    fileSize: 42_000_000,
    fileType: 'ZIP (JSON)',
    version: '2.4.1',
    rating: 4.8,
    sales: 862,
    updatedAt: daysAgo(13),
  },
  {
    id: 'prd_03',
    slug: 'ebook-digital-product-playbook',
    title: 'Digital Product Playbook 2026',
    category: 'ebook',
    price: 89_000,
    shortDescription:
      'Panduan 180 halaman membangun bisnis produk digital dari nol.',
    description:
      'Ebook praktis berisi kerangka kerja lengkap untuk riset ide, validasi pasar, produksi, hingga strategi peluncuran produk digital. Dilengkapi 24 studi kasus nyata dan template spreadsheet untuk proyeksi pendapatan.',
    cover:
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=900&q=80',
    highlights: [
      '180 halaman, format PDF & EPUB',
      '24 studi kasus produk digital lokal',
      'Template proyeksi revenue (Google Sheets)',
      'Checklist peluncuran 30 hari',
    ],
    includes: [
      { label: 'Format', value: 'PDF, EPUB' },
      { label: 'Halaman', value: '180' },
      { label: 'Bahasa', value: 'Indonesia' },
    ],
    fileSize: 28_000_000,
    fileType: 'PDF + EPUB',
    version: '1.5.0',
    rating: 4.7,
    sales: 2130,
    updatedAt: daysAgo(21),
  },
  {
    id: 'prd_04',
    slug: 'prompt-ai-mega-vault',
    title: 'Prompt AI Mega Vault — 1200 Prompt',
    category: 'prompt-ai',
    price: 119_000,
    originalPrice: 199_000,
    shortDescription:
      '1200 prompt teruji untuk copywriting, coding, riset, dan desain.',
    description:
      'Kumpulan 1200 prompt yang dikurasi dan diuji pada model modern seperti GPT, Claude, dan Gemini. Dikelompokkan dalam 18 kategori pekerjaan dengan struktur role-context-task-format yang konsisten sehingga output jauh lebih presisi.',
    cover:
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=900&q=80',
    highlights: [
      '1200 prompt dalam 18 kategori',
      'Struktur RCTF (Role-Context-Task-Format)',
      'Notion database + CSV siap import',
      'Update bulanan prompt baru',
    ],
    includes: [
      { label: 'Format', value: 'Notion, CSV, PDF' },
      { label: 'Jumlah', value: '1200 prompt' },
      { label: 'Model', value: 'GPT, Claude, Gemini' },
    ],
    fileSize: 12_000_000,
    fileType: 'ZIP',
    version: '4.0.2',
    rating: 4.9,
    sales: 1741,
    updatedAt: daysAgo(3),
  },
  {
    id: 'prd_05',
    slug: 'saas-starter-source-code',
    title: 'SaaS Starter Kit — React + Laravel',
    category: 'source-code',
    price: 399_000,
    originalPrice: 699_000,
    shortDescription:
      'Boilerplate production-ready: auth, billing, dashboard, multi-tenant.',
    description:
      'Starter kit lengkap untuk membangun SaaS: autentikasi Sanctum, manajemen tim multi-tenant, integrasi payment gateway, dashboard analitik, dan sistem role-permission. Ditulis dengan TypeScript strict dan test coverage 80%+.',
    cover:
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=900&q=80',
    highlights: [
      'React 19 + Laravel 12 + MySQL',
      'Auth, billing, multi-tenant, RBAC',
      'CI/CD pipeline + Docker compose',
      'Dokumentasi setup 40 halaman',
    ],
    includes: [
      { label: 'Stack', value: 'React, Laravel, MySQL' },
      { label: 'Lisensi', value: 'Single commercial project' },
      { label: 'Support', value: '6 bulan' },
    ],
    fileSize: 96_000_000,
    fileType: 'ZIP (Git repo)',
    version: '1.8.0',
    rating: 5,
    sales: 419,
    updatedAt: daysAgo(9),
  },
  {
    id: 'prd_06',
    slug: 'canva-pitch-deck-master',
    title: 'Pitch Deck Master — 80 Slide Canva',
    category: 'canva',
    price: 99_000,
    shortDescription:
      '80 slide investor-ready dengan struktur storytelling yang terbukti.',
    description:
      'Template pitch deck yang mengikuti struktur narasi startup modern: problem, solution, market, traction, business model, team, dan ask. Setiap slide dilengkapi catatan penulisan agar isi deck tetap tajam.',
    cover:
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=900&q=80',
    highlights: [
      '80 slide siap pakai',
      'Catatan penulisan tiap slide',
      'Chart & infografis editable',
      'Versi light & dark',
    ],
    includes: [
      { label: 'Format', value: 'Canva Template Link' },
      { label: 'Slide', value: '80' },
      { label: 'Lisensi', value: 'Personal & Komersial' },
    ],
    fileSize: 64_000_000,
    fileType: 'Canva Link',
    version: '2.1.0',
    rating: 4.6,
    sales: 1156,
    updatedAt: daysAgo(28),
  },
  {
    id: 'prd_07',
    slug: 'ebook-copywriting-conversion',
    title: 'Copywriting yang Menjual',
    category: 'ebook',
    price: 79_000,
    shortDescription:
      'Formula copywriting untuk landing page, iklan, dan email marketing.',
    description:
      'Panduan taktis menulis copy yang mengonversi. Berisi 40 formula headline, kerangka sales page, dan 60 contoh swipe file lokal yang bisa langsung diadaptasi untuk berbagai industri.',
    cover:
      'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=900&q=80',
    highlights: [
      '40 formula headline siap pakai',
      '60 swipe file berbahasa Indonesia',
      'Kerangka sales page lengkap',
      'Worksheet latihan menulis',
    ],
    includes: [
      { label: 'Format', value: 'PDF' },
      { label: 'Halaman', value: '132' },
      { label: 'Bahasa', value: 'Indonesia' },
    ],
    fileSize: 18_000_000,
    fileType: 'PDF',
    version: '1.2.0',
    rating: 4.8,
    sales: 934,
    updatedAt: daysAgo(41),
  },
  {
    id: 'prd_08',
    slug: 'elementor-ecommerce-woo-kit',
    title: 'WooCommerce Store Kit',
    category: 'elementor',
    price: 279_000,
    shortDescription:
      'Template toko online lengkap: katalog, produk, cart, dan checkout.',
    description:
      'Kit Elementor khusus WooCommerce dengan halaman katalog, detail produk, keranjang, checkout, dan akun pelanggan yang sudah dioptimasi untuk konversi mobile. Termasuk komponen trust badge dan upsell block.',
    cover:
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80',
    highlights: [
      '9 halaman toko lengkap',
      'Komponen upsell & trust badge',
      'Mobile checkout optimized',
      'Kompatibel WooCommerce 9+',
    ],
    includes: [
      { label: 'Format', value: 'JSON Template Kit' },
      { label: 'Halaman', value: '9' },
      { label: 'Lisensi', value: 'Unlimited project' },
    ],
    fileSize: 56_000_000,
    fileType: 'ZIP (JSON)',
    version: '1.9.3',
    rating: 4.7,
    sales: 512,
    updatedAt: daysAgo(17),
  },
  {
    id: 'prd_09',
    slug: 'source-code-landing-templates',
    title: 'Tailwind Landing Components',
    category: 'source-code',
    price: 189_000,
    shortDescription:
      '120 komponen landing page React + Tailwind siap copy-paste.',
    description:
      'Library komponen landing page berbasis React 19 dan Tailwind CSS 4. Semua komponen accessible, mendukung dark mode, dan bebas dependency berat sehingga mudah ditempel ke project mana pun.',
    cover:
      'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=900&q=80',
    highlights: [
      '120 komponen React + Tailwind',
      'Dark mode & a11y ready',
      'Zero heavy dependency',
      'TypeScript strict',
    ],
    includes: [
      { label: 'Stack', value: 'React 19, Tailwind 4' },
      { label: 'Komponen', value: '120' },
      { label: 'Lisensi', value: 'Unlimited project' },
    ],
    fileSize: 34_000_000,
    fileType: 'ZIP',
    version: '3.0.1',
    rating: 4.9,
    sales: 703,
    updatedAt: daysAgo(2),
  },
]

export const mockOwnedProducts: OwnedProduct[] = [
  {
    id: 'own_01',
    product: mockProducts[0],
    status: 'active',
    purchasedAt: daysAgo(52),
    downloadCount: 4,
    lastDownloadedAt: daysAgo(5),
  },
  {
    id: 'own_02',
    product: mockProducts[3],
    status: 'active',
    purchasedAt: daysAgo(23),
    downloadCount: 2,
    lastDownloadedAt: daysAgo(11),
  },
  {
    id: 'own_03',
    product: mockProducts[2],
    status: 'active',
    purchasedAt: daysAgo(8),
    downloadCount: 1,
    lastDownloadedAt: daysAgo(8),
  },
  {
    id: 'own_04',
    product: mockProducts[8],
    status: 'pending',
    purchasedAt: daysAgo(0),
    downloadCount: 0,
    lastDownloadedAt: null,
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: 'trx_01',
    invoiceNumber: 'INV-2026-000241',
    product: mockProducts[8],
    amount: 189_000,
    status: 'pending',
    paymentMethod: null,
    invoiceUrl: 'https://mayar.link/invoice/demo-241',
    createdAt: daysAgo(0),
    paidAt: null,
  },
  {
    id: 'trx_02',
    invoiceNumber: 'INV-2026-000198',
    product: mockProducts[2],
    amount: 89_000,
    status: 'paid',
    paymentMethod: 'QRIS',
    invoiceUrl: 'https://mayar.link/invoice/demo-198',
    createdAt: daysAgo(8),
    paidAt: daysAgo(8),
  },
  {
    id: 'trx_03',
    invoiceNumber: 'INV-2026-000154',
    product: mockProducts[3],
    amount: 119_000,
    status: 'paid',
    paymentMethod: 'BCA Virtual Account',
    invoiceUrl: 'https://mayar.link/invoice/demo-154',
    createdAt: daysAgo(23),
    paidAt: daysAgo(23),
  },
  {
    id: 'trx_04',
    invoiceNumber: 'INV-2026-000101',
    product: mockProducts[5],
    amount: 99_000,
    status: 'expired',
    paymentMethod: null,
    invoiceUrl: 'https://mayar.link/invoice/demo-101',
    createdAt: daysAgo(37),
    paidAt: null,
  },
  {
    id: 'trx_05',
    invoiceNumber: 'INV-2026-000077',
    product: mockProducts[0],
    amount: 149_000,
    status: 'paid',
    paymentMethod: 'GoPay',
    invoiceUrl: 'https://mayar.link/invoice/demo-077',
    createdAt: daysAgo(52),
    paidAt: daysAgo(52),
  },
]

export const mockDownloads: DownloadHistory[] = [
  {
    id: 'dl_01',
    product: mockProducts[0],
    fileName: 'social-media-kit-pro-v3.2.0.zip',
    fileSize: 184_000_000,
    downloadedAt: daysAgo(5),
    ip: '182.253.11.42',
  },
  {
    id: 'dl_02',
    product: mockProducts[2],
    fileName: 'digital-product-playbook-2026.pdf',
    fileSize: 28_000_000,
    downloadedAt: daysAgo(8),
    ip: '182.253.11.42',
  },
  {
    id: 'dl_03',
    product: mockProducts[3],
    fileName: 'prompt-ai-mega-vault-v4.0.2.zip',
    fileSize: 12_000_000,
    downloadedAt: daysAgo(11),
    ip: '114.10.28.199',
  },
  {
    id: 'dl_04',
    product: mockProducts[0],
    fileName: 'social-media-kit-pro-v3.1.0.zip',
    fileSize: 179_000_000,
    downloadedAt: daysAgo(30),
    ip: '114.10.28.199',
  },
  {
    id: 'dl_05',
    product: mockProducts[3],
    fileName: 'prompt-ai-mega-vault-v3.9.0.zip',
    fileSize: 11_400_000,
    downloadedAt: daysAgo(44),
    ip: '182.253.11.42',
  },
]

export const mockAdminStats: AdminStats = {
  revenue: 184_750_000,
  revenueGrowth: 18.4,
  orders: 1246,
  ordersGrowth: 12.1,
  users: 3872,
  usersGrowth: 9.6,
  products: 9,
  productsGrowth: 2,
  revenueSeries: [
    { month: 'Mar', revenue: 18_400_000, orders: 121 },
    { month: 'Apr', revenue: 21_900_000, orders: 148 },
    { month: 'Mei', revenue: 19_700_000, orders: 133 },
    { month: 'Jun', revenue: 26_800_000, orders: 178 },
    { month: 'Jul', revenue: 31_200_000, orders: 206 },
    { month: 'Agu', revenue: 38_600_000, orders: 244 },
  ],
  userGrowthSeries: [
    { month: 'Mar', users: 2410 },
    { month: 'Apr', users: 2698 },
    { month: 'Mei', users: 2941 },
    { month: 'Jun', users: 3204 },
    { month: 'Jul', users: 3536 },
    { month: 'Agu', users: 3872 },
  ],
  categoryBreakdown: [
    { category: 'Canva', value: 38 },
    { category: 'Elementor', value: 22 },
    { category: 'Prompt AI', value: 18 },
    { category: 'Ebook', value: 13 },
    { category: 'Source Code', value: 9 },
  ],
  popularProducts: [
    { id: 'prd_03', title: 'Digital Product Playbook 2026', sales: 2130, revenue: 189_570_000 },
    { id: 'prd_04', title: 'Prompt AI Mega Vault', sales: 1741, revenue: 207_179_000 },
    { id: 'prd_01', title: 'Social Media Kit Pro', sales: 1284, revenue: 191_316_000 },
    { id: 'prd_07', title: 'Copywriting yang Menjual', sales: 934, revenue: 73_786_000 },
    { id: 'prd_02', title: 'Elementor Agency Landing Pack', sales: 862, revenue: 214_638_000 },
  ],
}

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'usr_01',
    name: 'Rizky Pratama',
    email: 'rizky@example.com',
    whatsapp: '081234567890',
    role: 'member',
    status: 'active',
    points: 1357,
    totalSpent: 357_000,
    productsOwned: 3,
    joinedAt: daysAgo(96),
  },
  {
    id: 'usr_02',
    name: 'Salsabila Putri',
    email: 'salsa@example.com',
    whatsapp: '081298765432',
    role: 'member',
    status: 'active',
    points: 1109,
    totalSpent: 728_000,
    productsOwned: 5,
    joinedAt: daysAgo(142),
  },
  {
    id: 'usr_03',
    name: 'Bagas Nugroho',
    email: 'bagas@example.com',
    whatsapp: '081377712345',
    role: 'member',
    status: 'active',
    points: 189,
    totalSpent: 189_000,
    productsOwned: 1,
    joinedAt: daysAgo(12),
  },
  {
    id: 'usr_04',
    name: 'Dewi Anggraini',
    email: 'dewi@example.com',
    whatsapp: '081455590001',
    role: 'member',
    status: 'suspended',
    points: 99,
    totalSpent: 99_000,
    productsOwned: 1,
    joinedAt: daysAgo(210),
  },
  {
    id: 'usr_admin',
    name: 'Admin Nura',
    email: 'admin@example.com',
    whatsapp: '081200001111',
    role: 'admin',
    status: 'active',
    points: 0,
    totalSpent: 0,
    productsOwned: 0,
    joinedAt: daysAgo(420),
  },
]

/* ------------------------------ Program poin ------------------------------ */

/** Saldo 1357 = 1000 bonus + 149 + 119 + 89 dari transaksi lunas. */
export const mockPointEntries: PointEntry[] = [
  {
    id: 'pe_04',
    type: 'adjusted',
    amount: 1000,
    description: 'Bonus pendaftaran member',
    createdAt: daysAgo(96),
  },
  {
    id: 'pe_03',
    type: 'earned',
    amount: 149,
    transactionId: 'trx_05',
    description: 'Pembelian Social Media Kit Pro — 300 Template Canva',
    createdAt: daysAgo(52),
  },
  {
    id: 'pe_02',
    type: 'earned',
    amount: 119,
    transactionId: 'trx_03',
    description: 'Pembelian Prompt AI Mega Vault — 1200 Prompt',
    createdAt: daysAgo(23),
  },
  {
    id: 'pe_01',
    type: 'earned',
    amount: 89,
    transactionId: 'trx_02',
    description: 'Pembelian Digital Product Playbook 2026',
    createdAt: daysAgo(8),
  },
]

export const mockAdminPointEntries: AdminPointEntry[] = [
  {
    id: 'ape_09',
    user: { id: 'usr_02', name: 'Salsabila Putri', email: 'salsa@example.com' },
    type: 'earned',
    amount: 249,
    description: 'Pembelian Elementor Agency Landing Pack',
    createdAt: daysAgo(2),
  },
  {
    id: 'ape_08',
    user: { id: 'usr_01', name: 'Rizky Pratama', email: 'rizky@example.com' },
    type: 'earned',
    amount: 89,
    description: 'Pembelian Digital Product Playbook 2026',
    createdAt: daysAgo(8),
  },
  {
    id: 'ape_07',
    user: { id: 'usr_02', name: 'Salsabila Putri', email: 'salsa@example.com' },
    type: 'redeemed',
    amount: 1000,
    description: 'Penukaran poin saat checkout',
    createdAt: daysAgo(6),
  },
  {
    id: 'ape_06',
    user: { id: 'usr_03', name: 'Bagas Nugroho', email: 'bagas@example.com' },
    type: 'earned',
    amount: 189,
    description: 'Pembelian Tailwind Landing Components',
    createdAt: daysAgo(1),
  },
  {
    id: 'ape_05',
    user: { id: 'usr_01', name: 'Rizky Pratama', email: 'rizky@example.com' },
    type: 'earned',
    amount: 119,
    description: 'Pembelian Prompt AI Mega Vault',
    createdAt: daysAgo(23),
  },
  {
    id: 'ape_04',
    user: { id: 'usr_04', name: 'Dewi Anggraini', email: 'dewi@example.com' },
    type: 'earned',
    amount: 99,
    description: 'Pembelian Pitch Deck Master',
    createdAt: daysAgo(37),
  },
  {
    id: 'ape_03',
    user: { id: 'usr_02', name: 'Salsabila Putri', email: 'salsa@example.com' },
    type: 'earned',
    amount: 1860,
    description: 'Pembelian SaaS Starter Kit',
    createdAt: daysAgo(45),
  },
  {
    id: 'ape_02',
    user: { id: 'usr_01', name: 'Rizky Pratama', email: 'rizky@example.com' },
    type: 'earned',
    amount: 149,
    description: 'Pembelian Social Media Kit Pro',
    createdAt: daysAgo(52),
  },
  {
    id: 'ape_01',
    user: { id: 'usr_01', name: 'Rizky Pratama', email: 'rizky@example.com' },
    type: 'adjusted',
    amount: 1000,
    description: 'Bonus pendaftaran member',
    createdAt: daysAgo(96),
  },
]

export const mockCoupons: Coupon[] = [
  {
    id: 'cpn_01',
    code: 'GRAFIS20',
    type: 'percentage',
    value: 20,
    minPurchase: 100_000,
    maxDiscount: 50_000,
    expiresAt: new Date(Date.now() + 60 * 86_400_000).toISOString(),
    description: 'Diskon 20%, maksimal Rp50.000',
    isActive: true,
  },
  {
    id: 'cpn_02',
    code: 'HEMAT50',
    type: 'fixed',
    value: 50_000,
    minPurchase: 200_000,
    expiresAt: new Date(Date.now() + 30 * 86_400_000).toISOString(),
    description: 'Potongan Rp50.000',
    isActive: true,
  },
  {
    id: 'cpn_03',
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minPurchase: 0,
    expiresAt: new Date(Date.now() + 90 * 86_400_000).toISOString(),
    description: 'Diskon 10% tanpa minimum belanja',
    isActive: true,
  },
  {
    id: 'cpn_04',
    code: 'PROMOLAMA',
    type: 'percentage',
    value: 25,
    minPurchase: 0,
    expiresAt: daysAgo(14),
    description: 'Promo lama (sudah berakhir)',
    isActive: true,
  },
]
